name: nlp
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.10
  - pytorch>=1.3.0
  - torchvision
  - tqdm
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pip
  - transformers