name: nlp
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.10
  - pytorch>=1.7.0
  - torchvision
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pip
  - transformers
  - tqdm
  - ipython
  - huggingface-hub
  - nbdime
  - jupytext